apiVersion: v1
data:
  .dockercfg: eyJjbWFrc2Fjci5henVyZWNyLmlvIjp7InVzZXJuYW1lIjoiY21ha3NhY3IiLCJwYXNzd29yZCI6IjE5K3BFS1lwQXAyQURTYlFXaDY0alJxSUY5YTVjZTM0IiwiZW1haWwiOiJudWxsIiwiYXV0aCI6IlkyMWhhM05oWTNJNk1Ua3JjRVZMV1hCQmNESkJSRk5pVVZkb05qUnFVbkZKUmpsaE5XTmxNelE9In19
kind: Secret
metadata:
  name: cmaks-image-pull-secret
type: kubernetes.io/dockercfg
