apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: arcTest
  namespace: azureml
spec:
  releaseName: arc-k8s-demo
  chart:
    git: msdata@vs-ssh.visualstudio.com:v3/msdata/Vienna/itp-backend
    ref: mingj/arc
    path: docs/deployment/Cmk8s/tools/installer/install-job-chart
  values:
    image: cmaksacr.azurecr.io/cmk8s/cicd/agent-setup:build_pipeline-2f6056c875244c63c96a6f1ab457d9fa32451cb5
    kube_conf: kubernetes
