apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: arctest
  namespace: azureml
spec:
  releaseName: arc-k8s-demo
  chart:
    git: https://github.com/Martin-Jia/arcTest.git
    ref: main
    path: install-job-chart
  values:
    image: cmaksacr.azurecr.io/cmk8s/cicd/agent-setup:build_pipeline-2f6056c875244c63c96a6f1ab457d9fa32451cb5
    kube_conf: kubernetes
